package de.peacei.demo.greenDAO.database;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.IdentityScopeType;

import de.peacei.demo.greenDAO.database.EventEntity;
import de.peacei.demo.greenDAO.database.AttendeeEntity;

import de.peacei.demo.greenDAO.database.EventEntityDao;
import de.peacei.demo.greenDAO.database.AttendeeEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig eventEntityDaoConfig;
    private final DaoConfig attendeeEntityDaoConfig;

    private final EventEntityDao eventEntityDao;
    private final AttendeeEntityDao attendeeEntityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        eventEntityDaoConfig = daoConfigMap.get(EventEntityDao.class).clone();
        eventEntityDaoConfig.initIdentityScope(type);

        attendeeEntityDaoConfig = daoConfigMap.get(AttendeeEntityDao.class).clone();
        attendeeEntityDaoConfig.initIdentityScope(type);

        eventEntityDao = new EventEntityDao(eventEntityDaoConfig, this);
        attendeeEntityDao = new AttendeeEntityDao(attendeeEntityDaoConfig, this);

        registerDao(EventEntity.class, eventEntityDao);
        registerDao(AttendeeEntity.class, attendeeEntityDao);
    }
    
    public void clear() {
        eventEntityDaoConfig.getIdentityScope().clear();
        attendeeEntityDaoConfig.getIdentityScope().clear();
    }

    public EventEntityDao getEventEntityDao() {
        return eventEntityDao;
    }

    public AttendeeEntityDao getAttendeeEntityDao() {
        return attendeeEntityDao;
    }

}
