package de.peacei.demo.greenDAO.database;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table EVENT_ENTITY (schema version 1).
 */
public class EventEntity {

    private Long id;
    private String name;
    private String location;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public EventEntity() {
    }

    public EventEntity(Long id) {
        this.id = id;
    }

    public EventEntity(Long id, String name, String location) {
        this.id = id;
        this.name = name;
        this.location = location;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    // following method will be kept when java-file gets generated again, labeled by keep-comments
    // KEEP METHODS - put your custom methods here
    public String toString() {
    	return this.getName() + " @ " + this.getLocation();
    }
    // KEEP METHODS END

}
